please:
	g++ main.c++ -I/home/johnwick/Documents/nnp/Interface@1/nn_f_p/include -L/home/johnwick/Documents/nnp/Interface@1/nn_f_p/lib -lpredicting -lClassifier -lMisc -lClassifier -lConstructor -lsetErrors -lfeedForward -lBackpropogation -lMath -lMatrix -lLayer -lNeuron -lNeuralNetwork -lSaveWeights -o main
